version: 1
send_anonymous_usage_stats: true
project_id: "tap-pixlet"
default_environment: test
environments:
- name: test
plugins:
  extractors:
  - name: "tap-pixlet"
    namespace: "tap_pixlet"
    pip_url: -e .
    capabilities:
    - state
    - catalog
    - discover
    - about
    - stream-maps
    settings:
    - name: path
    - name: installation_id
    - name: background
      kind: boolean
    - name: app_config
      kind: object
    config:
      path: example
  loaders:
  - name: target-webp
    namespace: target_webp
    pip_url: git+https://github.com/DouweM/target-webp.git
    capabilities:
    - about
    - stream-maps
    - record-flattening
jobs:
- name: example
  tasks:
  - tap-pixlet target-webp
